=== UnfoldedInc/basemap-layers/schema/root.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "deckgl-style-spec",
  "type": "object",
  "additionalProperties": false,
  "title": "deck.gl Style Specification",
  "required": [
    "layers",
    "sources",
    "version"
  ],
  "properties": {
    "version": {
      "type": "integer",
      "enum": [1]
    },
    "id": {
      "type": "string"
    },
    "metadata": {
      "type": "object"
    },
    "name": {
      "type": "string",
      "description": "Name of style"
    },
    "sources": {
      "type": "object"
    },
    "sprite": {
      "type": "string"
    },
    "glyphs": {
      "type": "string"
    },
    "layers": {
      "type": "array",
      "items": {
        "$ref": "layer.json#/definitions/Layer"
      }
    }
  }
}

=== UnfoldedInc/basemap-layers/examples/example2.json
{
  "version": 1,
  "name": "Example 2",
  "sources": {
    "openmaptiles": {
      "type": "vector",
      "url": "https://api.maptiler.com/tiles/v3/tiles.json?key={key}"
    }
  },
  "sprite": "https://maputnik.github.io/osm-liberty/sprites/osm-liberty",
  "glyphs": "https://api.maptiler.com/fonts/{fontstack}/{range}.pbf?key={key}",
  "layers": [
    {
      "id": "example_textlayer",
      "type": "TextLayer",
      "source": "natural_earth_shaded_relief",
      "maxzoom": 6,
      "sizeScale": 1,
      "paint": {"raster-opacity": {"base": 1.5, "stops": [[0, 0.6], [6, 0.1]]}}
    }
  ]

}
